backend:
  name: github
  repo: jtkoch/Gatsby-Portfolio
  branch: master
media_folder: static/assets
public_folder: assets
display_url: https://www.jensenkoch.com/
collections:
  - name: blog
    label: Blog
    folder: blog
    create: true
    fields:
      - { name: path, label: Path, default: /blog/ }
      - { name: date, label: Date, widget: datetime }
      - { name: title, label: Title }
      - { name: image, label: Image, widget: image }
      - { name: body, label: Body, widget: markdown }